apiVersion: batch/v1
kind: Job
metadata:
  name: image-builder-{{ .Values.serviceName | lower }}
  labels:
    app.kubernetes.io/name: kaniko
    app.kubernetes.io/component: image-builder
    service-name: {{ .Values.serviceName }}
    release-name: {{ .Release.Name }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never

      volumes:
        # Mount specified PVC or use local mount
        {{- if .Values.workspaceVolumePvc }}
        - name: workspace-mount
          persistentVolumeClaim:
            claimName: {{ .Values.workspaceVolumePvc }}
        {{- else }}
        - name: workspace-mount
          hostPath:
            path: /opensearch-migrations
            type: DirectoryOrCreate
        {{- end }}

      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - --context=/workspace/{{ .Values.contextDir }}
            - --dockerfile=/workspace/{{ .Values.contextDir }}/Dockerfile
            - --destination={{ .Values.registryDestination }}
            {{- range $key, $value := .Values.buildArgs }}
            - --build-arg={{ $key }}={{ $value }}
            {{- end }}
            - --cache=true
            - --insecure
            - --insecure-pull
            - --skip-tls-verify
          volumeMounts:
            - name: workspace-mount
              mountPath: /workspace
              readOnly: true
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "6Gi"
