name: python-tests

on: [push, pull_request]

jobs:
  test-linux:
    strategy:
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Upgrades Directory
        uses: Bhacaz/checkout-files@v2
        with:
          files: upgrades
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Run Tests
        run: |
          python -m pytest tests/