---
name: Check if the workflow requires approval
on:
  workflow_call:
    outputs:
      is-require-approval:
        description: The CI image version for Linux build
        value: ${{ jobs.require-approval.outputs.output-is-require-approval }}

jobs:
  require-approval:
    runs-on: ubuntu-latest
    outputs:
      output-is-require-approval: ${{ steps.step-is-require-approval.outputs.is-require-approval }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - name: Get CodeOwner List
        id: step-is-require-approval
        run: |
          github_event=${{ github.event_name }}
          author=${{ github.event.pull_request.user.login }}
          echo "Push event does not need approval."
          echo "is-require-approval=migrations-cicd" >> $GITHUB_OUTPUT
