name: Jenkins E2E

on:
  push:
  pull_request:

env:
  python-version: '3.11'

jobs:
  rfs-e2e-aws-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jenkins/webhookTriggers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
      - name: Install dependencies for python webhook
        run: |
          python3 -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Trigger jenkins job and wait for completion
        run: |
          branch_name=$(jq --raw-output .pull_request.head.ref $GITHUB_EVENT_PATH)
          pr_repo_url=$(jq --raw-output .pull_request.head.repo.clone_url $GITHUB_EVENT_PATH)
          echo "Running jenkins test on repo: $pr_repo_url and branch: $branch_name"
          pipenv run python3 default_webhook_trigger.py --pipeline_token=${{ secrets.JENKINS_MIGRATIONS_GENERIC_WEBHOOK_TOKEN }} --payload='{"pipeline_name": "rfs-default-e2e-test", "GIT_REPO_URL": "$pr_repo_url", "GIT_BRANCH": "$branch_name"}' --job_name=rfs-default-e2e-test
