name: Jenkins

on:
  push:
    branches-ignore:
      - 'backport/**'
      - 'dependabot/**'
  pull_request_target:
    types: [opened, synchronize, reopened]

env:
  python-version: '3.11'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  rfs-e2e-aws-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref || github.ref_name }}
          REPO_BASE: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      - name: Jenkins Job Trigger and Monitor
        uses: lewijacn/jenkins-trigger@1.0.4
        with:
          jenkins_url: "https://migrations.ci.opensearch.org"
          job_name: "rfs-default-e2e-test"
          api_token: "${{ secrets.JENKINS_MIGRATIONS_GENERIC_WEBHOOK_TOKEN }}"
          job_params: "GIT_REPO_URL=https://github.com/$REPO_BASE.git,GIT_BRANCH=$BRANCH_NAME"
